### ISSUE TITLE
일정 - 일정 수정 API

### ISSUE THREAD

**Issue by f1v3-dev** [dnd-side-project/dnd-11th-7-backend#112]
## 🛠️ 어떤 기능인가요?

회원의 일정을 수정하는 API 기능 개발을 진행합니다.

기존에 일정을 수정하는 메서드가 있었으나, 요청할 때의 정보가 다르다는 것을 까먹고 있었네요 😅

- 비회원: 모임 UUID, 일정 UUID, 일정 수정 요청 DTO
- 회원: 모임 UUID, **Authorization Header(AT)**, 일정 수정 요청 DTO

이에 맞게 새로운 REST API 구현을 해야 합니다.

## 🗒️ 작업 상세 내용

- [x] 회원 일정 수정 API 구현

## 👀 질문

_비회원 일정 수정 API_

```http
PATCH /api/v1/meetings/{meetingUuid}/schedules/{scheduleUuid}
```

위와 같이 비회원 일정 수정 API의 엔드포인트를 구성해두었는데 회원의 경우 어떻게 해야될까요?

_예시_
```http
PATCH /api/v1/meetings/{meetingUuid}/schedules
```

이렇게 구성한 REST API도 괜찮을까요? 아니면 더 좋은 방식이 있는지 태웅님의 의견도 궁금해요 !

@RTUnu12

**Comment by RTUnu12** [comment]
음...uuid를 노출시키기 보다는 requestbody로 하는게 좋지 않을까요?
다만 불평하면 저렇게 해도 상관없긴해요

**Comment by f1v3-dev** [comment]
> 음...uuid를 노출시키기 보다는 requestbody로 하는게 좋지 않을까요? 다만 불평하면 저렇게 해도 상관없긴해요

UUID는 sequence number가 아니여서 추측하기엔 어려워서 상관없다고 생각을 했어요. 자원에 대한 식별자는 body에 담는 것보단 URI에 나타내는게 자연스럽다고 생각을 했어요

**Comment by f1v3-dev** [comment]
앗 그리구 제가 물어본 질문의 의도는 아래의 회원 일정 수정 URI 구성에 대해서 여쭤본거였습니다

**Comment by RTUnu12** [comment]
음...괜찮아보이긴 합니다. 여기서 더 좋은 방법이 있을까? 싶기도 하고

**Comment by f1v3-dev** [comment]
> 음...괜찮아보이긴 합니다. 여기서 더 좋은 방법이 있을까? 싶기도 하고

그러면 일단 저렇게 진행을 하겠습니다! 나중에 고칠점이 보이면 리팩토링 해볼게요
