### ISSUE TITLE
일정 수정이 불가능한 문제

### ISSUE THREAD

**Issue by RTUnu12** [dnd-side-project/dnd-11th-7-backend#148]
## 🚨 어떤 버그인가요?

* 회원/비회원일때 일정 수정이 불가능함

## 💥 어떤 상황에서 발생한 버그인가요?

1. 일정을 입력한 상황에서 수정
![image](https://github.com/user-attachments/assets/a187de1e-41ce-4478-9177-fcfd8253f5b1)
2. 일정 수정 누르기
![image](https://github.com/user-attachments/assets/fe763ef8-1d0b-42ce-a1fe-0bf5d503fbaa)
3. 오류 발생
![image](https://github.com/user-attachments/assets/d425b56c-f753-42ab-86a6-b58cf776f2c9)

## 💡 예상 결과
* 수정이 되어야 하는데 다시 수정을 누를 경우 수정이 되지 않음. (비회원도 똑같이 발생)
![image](https://github.com/user-attachments/assets/bb51958b-edd6-4af9-abe1-d501d1dbe5c4)
![image](https://github.com/user-attachments/assets/f0048537-d88d-434d-82ce-9b58617d64c0)

**Comment by f1v3-dev** [comment]
태웅님이 올려주신 사진에서 요청 URI를 보니

```http
PATCH /api/v1/meetings/{meetingUuid}/schedules
```

위의 주소로 보내서 그런 것 같아요! 

**회원인 경우**

```http
PATCH /api/v1/meetings/{meetingUuid}/schedules/members
```

**비회원인 경우**

```http
PATCH /api/v1/meetings/{meetingUuid}/schedules/guests/{scheduleUuid}
```

이렇게 수정을 했었는데 이것도 제가 전달을 안했었나(?)봐요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 
프론트 분들에게 말씀드려야겠어요

**Comment by RTUnu12** [comment]
아하 알겠습니다
