### ISSUE TITLE
일정 API

### ISSUE THREAD

**Issue by f1v3-dev** [dnd-side-project/dnd-11th-7-backend#30]
#### 1. 일정 생성

이 전에 작업한 모임이 정상적으로 생성될 때 다음과 같은 일정을 생성해야 합니다.
- 모임 인원 수 만큼의 일정을 미리 생성합니다.
- 미리 생성된 일정은 각각 고유의 UUID를 가지고 있습니다.

## 🗒️ 작업 상세 내용

- [x] 일정 엔티티 매핑
- [x] 일정 생성 API 구현
- [x] 모임 생성 비즈니스 로직에 모임 인원 수 만큼 일정 생성

**Comment by f1v3-dev** [comment]
일정을 할당할 때 (사용자가 일정 생성 요청을 보낼 때) 일정 날짜도 같이 보내게 됩니다.

이를 처리하기 위해 **일정 날짜(Date of Schedule)** 에 대한 작업을 함께 진행하겠습니다.

_ERD Cloud_
<img width="891" alt="image" src="https://github.com/user-attachments/assets/20934274-5956-4f19-a339-a857604a162a">

---

추가적으로, DB상으로 테이블이 별도로 존재하지만 일정을 생성할 때 일정 날짜도 같이 생성되고, 일정이 삭제될 경우 같이 삭제 되어야합니다.
이러한 경우, `일정(Schedule)`과 `일정 날짜(Date_of_Schedule)`에서의 연관관계는 `OneToMany`로 설정하는게 좋아보이는데 어떤가요?
태웅님(@RTUnu12)의 의견이 궁금합니다! 👀

**Comment by RTUnu12** [comment]
일정에 여러 날짜가 존재한다는 것이군요...
전 좋은거 같아요.
다만 한 일정에 여러 날짜가 존재할 수 있는지는 잘 모르겠습니다.
