### ISSUE TITLE
OAuth 로그인 로직 수정 

### ISSUE THREAD

**Issue by f1v3-dev** [dnd-side-project/dnd-11th-7-backend#63]
## 🛠️ 어떤 기능인가요?
- OAuth 로그인 로직을 수정합니다. (AT, RT 쿠키로 제공?)
- 카카오 로그인 테스트 페이지를 만듭니다. (Thyemleaf 사용) 

## 🗒️ 작업 상세 내용

- [x] Controller 생성 (로그인 요청)
- [x] View (Thyemleaf)
- [x] OAuth 로그인 로직 수정

**Comment by f1v3-dev** [comment]
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/0905dadf-8c1a-48fd-9fee-f997d50f0ae3">

---

중간에 카카오 로그인 페이지를 띄우는 과정 등 302 REDIRECT 과정이 포함되어있음. (cross-origin)
이러한 문제로 인해, 응답 헤더 Authorization 설정을 해줘도 사라지는 것

쿠키로 발급하고 프론트 측에서 다시 요청해서 헤더로 받던지 아니면 쿠키만을 사용하던지 둘 중 하나의 방법으로 진행하는 방식으로 변경해야 할 듯

> 모르는게 아직도 많다...ㅠㅠ

**Comment by RTUnu12** [comment]
역시 리다이렉트 땜에 사라지는 것이였네요...
