### ISSUE TITLE
[question] 일정 할당 - 모임 ID의 위치 

### ISSUE THREAD

**Issue by f1v3-dev** [dnd-side-project/dnd-11th-7-backend#85]
## 🙋 질문 내용
현재 구현되어있는 API 에서 요청 Body에 `meetingId` 를 넘겨주는 방식으로 구현이 되어있는데 
해당 방식보단, URI에서 받는게 좋지 않을까 생각합니다.

```json
{
  "dateOfScheduleList": [
    {
      "startTime": "2024-08-19T09:00:00",
      "endTime": "2024-08-19T11:00:00",
      "rank": 1
    },
    {
      "startTime": "2024-08-20T09:00:00",
      "endTime": "2024-08-20T10:00:00",
      "rank": 2
    },
    {
      "startTime": "2024-08-21T11:00:00",
      "endTime": "2024-08-21T12:00:00",
      "rank": 3
    }
  ],
  "nickName": "정승조",
  "meetingId": 6
}
```

어떻게 생각하시는지 궁금합니다 !

## 👀 참고할만한 자료(선택)

X

**Comment by RTUnu12** [comment]
전에 meetingId는 URL에 드러내고 싶지 않기를 원하신 것 아니였나요?
상관...은 없습니다

**Comment by f1v3-dev** [comment]
> 전에 meetingId는 URL에 드러내고 싶지 않기를 원하신 것 아니였나요? 상관...은 없습니다

단순하게 Request Body에 넣어서 보냈던 것 같아요! 그래서 조금 잘못 설계한 것 같습니다.
REST API를 설계할 때 자원(resource)에 대한 명시를 해줘야 할텐데 제가 조금 API 설계에 신경쓰지 못했네요 ㅠㅠ

**기존**

```http
POST /api/v1/schedules/members/assign

{
  "dateOfScheduleList": [
    {
      "startTime": "2024-08-19T09:00:00",
      "endTime": "2024-08-19T11:00:00",
      "rank": 1
    },
    {
      "startTime": "2024-08-20T09:00:00",
      "endTime": "2024-08-20T10:00:00",
      "rank": 2
    },
    {
      "startTime": "2024-08-21T11:00:00",
      "endTime": "2024-08-21T12:00:00",
      "rank": 3
    }
  ],
  "nickName": "정승조",
  "meetingId": 6
}
```

**변경**

```http
POST /api/v1/meetings/{meetingId}/schedules/members/assign

{
  "dateOfScheduleList": [
    {
      "startTime": "2024-08-19T09:00:00",
      "endTime": "2024-08-19T11:00:00",
      "rank": 1
    },
    {
      "startTime": "2024-08-20T09:00:00",
      "endTime": "2024-08-20T10:00:00",
      "rank": 2
    },
    {
      "startTime": "2024-08-21T11:00:00",
      "endTime": "2024-08-21T12:00:00",
      "rank": 3
    }
  ],
  "nickName": "정승조"
}
```

이런식으로 변경하는게 조금 더 낫지 않을까 생각이 듭니다.

**Comment by RTUnu12** [comment]
아하...좋은것 같습니다!

**Comment by f1v3-dev** [comment]
아 그리고 생각을 해보니까 ID(Auto Increment) 값보다는 모임 UUID를 사용하는게 보안상 더 좋아보이네요! 

`POST /api/v1/meetings/{meetingUuid}/schedules/members/assign`

이런식으로 할까요? 뭔가 URI가 너무 길어서 별로인 것 같기도 한데 혹시 추천해주실만한 URI 있을까요?

**Comment by f1v3-dev** [comment]
> 참고: https://developers.worksmobile.com/kr/docs/board-post-comment-put

위의 내용처럼, 일정을 수정하기 위해서는 모임의 ID, 일정의 ID  상위 계층에 대한 정보도 필요하도록 API 구성합니다. 
1개의 모임에는 여러개의 일정이 존재할 수 있는 것을 고려하고 API를 수정하도록 할게요!

**Comment by f1v3-dev** [comment]
아 그리구, 회원/비회원에 대한 API는 아무래도 분리하는게 좋을 것 같아요. 

같은 API로 받을 경우에 화이트 리스트 처리를 해야하는데, 이러한 경우에 별도로 헤더 검증을 통해서 회원 검증을 해야하는 JWT Filter를 제대로 사용하지 않는(?) 더 이상한 방식으로 변해버리는 것 같더라구요. 

오히려 코드 수를 줄일려고 한건데 Controller 측에서는 줄어들었을지 몰라도, Service Layer 측에서 해야할 일이 더 늘어나는 웃긴 상황인 것 같아서 **회원/비회원 API는 분리** 하는게 좋아보입니다.
