### ISSUE TITLE
예외 처리 - 서버 에러 (500)

### ISSUE THREAD

**Issue by f1v3-dev** [dnd-side-project/dnd-11th-7-backend#92]
## 🙋 질문 내용

제가 `ExceptionController` 를 만들면서 서버측에서 발생한 에러를 클라이언트로 보내도록 구성을 하였는데
생각을 해보니 로그(log.error)를 작성해서 어떤 에러가 발생했는지에 대해 로깅이 필요해보입니다. 

다음과 같이 수정을 해보고자 하는데 어떤 방식이 좋을까요? 

1. 서버측에 로그만 작성
2. 클라이언트로 에러가 발생한 이유 보내기 + 서버 측 로그 작성
3. 2번의 방식에서 정확한 이유 (`e.getMessage()`)는 숨기고 보내기 - 단순히, 서버에서 에러가 발생하였습니다. 같이 메시지 작성

## 👀 참고할만한 자료

_소스코드_

```java
    /**
     * Exception 예외 처리 (Server Error)
     *
     * @param e Exception
     * @return ErrorResponse (에러 응답 - code, message)
     */
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handleException(Exception e) {
        ErrorResponse body = ErrorResponse.builder()
                .code("500")
                .message(e.getMessage())
                .build();

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(body);
    }
```

**Comment by RTUnu12** [comment]
개발할 때는 2번이 좋기는 한데 이제 실제로 서비스할 땐 3번이 좋을 거 같아요.

**Comment by f1v3-dev** [comment]
3번으로 진행하겠습니다~
